apiVersion: v1
kind: Service
metadata:
  name: custom-app
  namespace: kuber-practice
spec:
  type: ClusterIP
  selector:
    app: custom-app
  ports:
    - name: http
      port: 80
      targetPort: http
