apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-dr
  namespace: kuber-practice
spec:
  host: app-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 3
      http:
        http1MaxPendingRequests: 5
    tls:
      mode: ISTIO_MUTUAL
